#define LINK_APPEND 0
#define LINK_SLOTIN 1
#define LINK_INSAFTER 2
#define LINK_INSBEFORE 3

#define LINK_FROMFIRST 0
#define LINK_FROMLAST 1
#define LINK_FROMENTRYAFT 2
#define LINK_FROMENTRYBFR 3

#define LINK_SPLITAFT 0
#define LINK_SPLITBFR 1
